import type { MapStyle } from '@/components/CityMapSvg'

export interface GalleryItem {
  id: number
  title: string
  city: string
  theme: string
  occasion: string
  description: string
  altText: string
  anchor: string
  mapStyle: MapStyle
}

export const galleryItems: GalleryItem[] = [
  {
    id: 1,
    title: 'New York City Map Print',
    city: 'New York',
    theme: 'Minimalist Monochrome',
    occasion: 'Housewarming Gift',
    description: 'Minimal monochrome NYC wall art styled for warm modern interiors. Perfect for gallery walls and reading nooks.',
    altText: 'Luxury New York city map print in warm beige modern living room',
    anchor: 'new-york',
    mapStyle: 'manhattan',
  },
  {
    id: 2,
    title: 'Paris Map Art Print',
    city: 'Paris',
    theme: 'Mediterranean Neutral',
    occasion: 'Anniversary Gift',
    description: 'Elegant Parisian street map rendered in warm travertine tones. Evokes the quiet luxury of a Haussmann apartment.',
    altText: 'Paris street map art print styled in editorial interior photography',
    anchor: 'paris',
    mapStyle: 'paris',
  },
  {
    id: 3,
    title: 'Tokyo Neighborhood Map',
    city: 'Tokyo',
    theme: 'Japandi Minimal',
    occasion: 'Personal Collection',
    description: 'Refined Tokyo street grid in soft ivory and charcoal. A study in negative space and urban geometry.',
    altText: 'Minimalist Tokyo map print in Japandi interior with warm lighting',
    anchor: 'tokyo',
    mapStyle: 'tokyo',
  },
  {
    id: 4,
    title: 'London City Map Art',
    city: 'London',
    theme: 'Heritage Cream',
    occasion: 'Housewarming Gift',
    description: "London's iconic street network captured in warm cream and walnut tones. A timeless addition to any home library.",
    altText: 'London city map print in warm editorial interior setting',
    anchor: 'london',
    mapStyle: 'london',
  },
  {
    id: 5,
    title: 'Barcelona Street Map Print',
    city: 'Barcelona',
    theme: 'Mediterranean Neutral',
    occasion: 'Travel Memory',
    description: "Eixample's grid and Gothic Quarter's labyrinth rendered in warm Mediterranean neutrals. Sun-bleached, architectural, enduring.",
    altText: 'Barcelona street map art print in Mediterranean interior with warm tones',
    anchor: 'mediterranean-vibes',
    mapStyle: 'barcelona',
  },
  {
    id: 6,
    title: 'Amsterdam Canal Map',
    city: 'Amsterdam',
    theme: 'Warm Minimal',
    occasion: 'Wedding Gift',
    description: 'The concentric canals of Amsterdam rendered in warm ivory and soft black. Elegant, architectural, and quietly romantic.',
    altText: 'Amsterdam canal map print in warm minimal interior',
    anchor: 'minimalist',
    mapStyle: 'amsterdam',
  },
  {
    id: 7,
    title: 'Rome Historic District Map',
    city: 'Rome',
    theme: 'Travertine Warm',
    occasion: 'Anniversary Gift',
    description: "Rome's ancient streets and piazzas immortalized in travertine and sand tones. A monument to editorial restraint.",
    altText: 'Rome map print styled in warm travertine editorial interior',
    anchor: 'mediterranean-vibes',
    mapStyle: 'rome',
  },
  {
    id: 8,
    title: 'Copenhagen Map Print',
    city: 'Copenhagen',
    theme: 'Scandinavian Minimal',
    occasion: 'Housewarming Gift',
    description: "Copenhagen's harbor and canal districts in understated Nordic tones. A tribute to Scandinavian design philosophy.",
    altText: 'Copenhagen city map print in Scandinavian minimal interior',
    anchor: 'minimalist',
    mapStyle: 'grid',
  },
  {
    id: 9,
    title: 'Los Angeles Neighborhood Map',
    city: 'Los Angeles',
    theme: 'Warm California',
    occasion: 'Personal Collection',
    description: "From Silver Lake to Venice Beach — LA's sprawling neighborhoods captured in a warm, sun-faded editorial palette.",
    altText: 'Los Angeles city map print in warm California interior setting',
    anchor: 'minimalist',
    mapStyle: 'grid',
  },
  {
    id: 10,
    title: 'Sydney Harbour Map Art',
    city: 'Sydney',
    theme: 'Coastal Neutral',
    occasion: 'Travel Memory',
    description: 'The harbour, the bays, the bridge — Sydney rendered in coastal neutrals and soft cartographic lines.',
    altText: 'Sydney harbour map print in coastal neutral interior',
    anchor: 'minimalist',
    mapStyle: 'grid',
  },
  {
    id: 11,
    title: 'New York Brooklyn Map',
    city: 'New York',
    theme: 'Urban Warm',
    occasion: 'Housewarming Gift',
    description: "Brooklyn's brownstone blocks and waterfront parks in warm matte tones. A love letter to neighborhood life.",
    altText: 'Brooklyn New York map print in warm urban interior',
    anchor: 'new-york',
    mapStyle: 'manhattan',
  },
  {
    id: 12,
    title: 'Paris Marais Quarter Map',
    city: 'Paris',
    theme: 'Soft Beige',
    occasion: 'Wedding Gift',
    description: 'The winding streets of Le Marais in a soft beige palette. Intimate in scale, grand in feeling.',
    altText: 'Paris Marais map art print in soft beige editorial interior',
    anchor: 'paris',
    mapStyle: 'paris',
  },
  {
    id: 13,
    title: 'Tokyo Shinjuku District Map',
    city: 'Tokyo',
    theme: 'Japandi Minimal',
    occasion: 'Personal Collection',
    description: "Shinjuku's dense street network in fine-line cartography on warm ivory. An urban meditation in print form.",
    altText: 'Tokyo Shinjuku map print in Japandi interior space',
    anchor: 'tokyo',
    mapStyle: 'tokyo',
  },
  {
    id: 14,
    title: 'London Notting Hill Map',
    city: 'London',
    theme: 'Heritage Cream',
    occasion: 'Travel Memory',
    description: 'Notting Hill and Portobello Road in warm cream and muted terracotta. Nostalgic without being sentimental.',
    altText: 'London Notting Hill map print in heritage cream interior',
    anchor: 'london',
    mapStyle: 'london',
  },
  {
    id: 15,
    title: 'Mediterranean Coastline Map',
    city: 'Amalfi Coast',
    theme: 'Mediterranean Neutral',
    occasion: 'Anniversary Gift',
    description: "The Amalfi Coast's dramatic topography rendered in warm earthy cartography. Brings the south to any interior.",
    altText: 'Mediterranean Amalfi Coast map print in warm earthy interior',
    anchor: 'mediterranean-vibes',
    mapStyle: 'grid',
  },
  {
    id: 16,
    title: 'New York Manhattan Grid',
    city: 'New York',
    theme: 'Architectural Monochrome',
    occasion: 'Office Decor',
    description: "Manhattan's perfectly ordered grid abstracted to its finest lines. Architectural precision as wall art.",
    altText: 'Manhattan grid city map print in architectural monochrome interior',
    anchor: 'new-york',
    mapStyle: 'manhattan',
  },
  {
    id: 17,
    title: 'Berlin Mitte Map Print',
    city: 'Berlin',
    theme: 'Bauhaus Neutral',
    occasion: 'Personal Collection',
    description: 'Berlin Mitte in warm greige and matte black. Raw, considered, and quietly powerful.',
    altText: 'Berlin Mitte map print in Bauhaus neutral editorial interior',
    anchor: 'minimalist',
    mapStyle: 'grid',
  },
  {
    id: 18,
    title: 'Kyoto Temple District Map',
    city: 'Kyoto',
    theme: 'Wabi-Sabi Warm',
    occasion: 'Housewarming Gift',
    description: "Kyoto's ancient temple paths in warm sand and muted ink. A quiet reverence for place and tradition.",
    altText: 'Kyoto temple district map print in wabi-sabi warm interior',
    anchor: 'tokyo',
    mapStyle: 'tokyo',
  },
  {
    id: 19,
    title: 'Lisbon Alfama Map Art',
    city: 'Lisbon',
    theme: 'Mediterranean Neutral',
    occasion: 'Travel Memory',
    description: "Alfama's hillside streets in warm terracotta and sun-bleached ivory. A map for those who prefer the slower road.",
    altText: 'Lisbon Alfama map print in Mediterranean neutral interior',
    anchor: 'mediterranean-vibes',
    mapStyle: 'rome',
  },
  {
    id: 20,
    title: 'New York City Gift Map',
    city: 'New York',
    theme: 'Warm Neutral',
    occasion: 'Housewarming Gift',
    description: 'A curated neighbourhood view of Manhattan in warm, gift-ready palette. The map print that says something.',
    altText: 'New York city map print as housewarming gift in warm neutral interior',
    anchor: 'housewarming',
    mapStyle: 'manhattan',
  },
]

export const featuredItems: GalleryItem[] = galleryItems.filter((_, i) => [0, 1, 2, 3, 4].includes(i))
